const folioList = Object.freeze({
  contents: [
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'NCSOFT',
      date: '2022-07 ~ 2022-08',
      title: 'NC SOFT PLAY NOVEL TL Story Map 페이지 구축',
      description: '',
      outLink: 'https://about.ncsoft.com/play-novel',
      img: './img/nc-playnovel.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: '네이버(주)',
      date: '2021-11 ~ 2022-01',
      title: 'NAVER VIBE 서비스 소개 페이지 리뉴얼 구축',
      description: '',
      outLink: 'https://vibe.naver.com/about/',
      img: './img/vibe.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2021-11 ~ 2022-01',
      title: 'NCP NAVER Cloud Summit 2021 웹사이트 구축 및 운영',
      description: '',
      outLink: 'https://www.ncloud-online.com/navercloudsummit2021/',
      img: './img/aisummit_2021.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'PC',
      client: 'CJ',
      date: '2021-09 ~ 2021-11',
      title: 'M3(mnet smart+) 웹사이트 구축',
      description: 'Home, Artist > Board, Contents, Vote 페이지',
      outLink: 'https://smart.mnetjp.com/',
      img: './img/mnet-smart.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2021-08 ~ 2021-10',
      title: 'NCP GAME X CONFERENCE 2021 웨비나 웹사이트 구축 및 운영',
      description: '',
      outLink: 'https://www.gamex.game/',
      img: './img/gamex.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Mobile',
      client: '아모레퍼시픽',
      date: '2021-05 ~ 2021-07',
      title: '그린사이클 캠페인 마이크로 사이트 구축',
      description: '',
      outLink: '',
      img: './img/amore_greencycle.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'ECOEX',
      date: '2021-04 ~ 2021-04',
      title: 'ECOEX LAB 웹사이트 리뉴얼 구축',
      description: '',
      outLink: 'https://ecoex.kr/',
      img: './img/ecoex.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'DL Holdings',
      date: '2020-11 ~ 2021-02',
      title: 'DL Holdings 웹사이트 구축',
      description: '',
      outLink: 'https://www.dlholdings.co.kr/ko/index.do',
      img: './img/dlholdings.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2020-11 ~ 2021-06',
      title: '네이버클라우드 웹사이트 리뉴얼 및 운영',
      description: '',
      outLink: 'https://navercloudcorp.com/',
      img: './img/navercloudcorp.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'profit',
      date: '2020-11 ~ 2020-12',
      title: 'profit 웹/태블릿 구축 - UI 개발(React)',
      description: '',
      outLink: '',
      img: './img/profit.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'SK그룹',
      date: '2020-09 ~ 2020-11',
      title: 'SK ICT TECH SUMMIT 2020 웹사이트 구축',
      description: '',
      outLink: '',
      img: './img/sk_ict-summit.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2020-09 ~ 2020-11',
      title: 'NCP 웨비나 웹사이트 구축(AI Summit)',
      description: '',
      outLink: 'https://www.ncloud-online.com/aisummit/',
      img: './img/aisummit_2020.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Tablet',
      client: 'POSCO 건설',
      date: '2020-05 ~ 2020-06',
      title: '더샵갤러리 홍보 어플리케이션 - 웹뷰(갤럭시 탭)',
      description: '',
      outLink: '',
      img: './img/thesharp-gallery.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Manage',
      siteInfo: 'Responsive',
      client: '디엘이앤씨㈜',
      date: '2020-03 ~ 2020-10',
      title: '대림산업 ACRO 아크로라이프 웹사이트 운영',
      description: '',
      outLink: '',
      img: './img/acro.jpg',
    },
    {
      type: 'Publishing',
      typeDetail: 'Manage',
      siteInfo: 'Adaptive',
      client: 'DDB Korea',
      date: '2020-03 ~ 2022-09',
      title: '하이투자증권 이벤트 웹사이트 연간 운영',
      description: '',
      outLink: 'https://event-hi-ib.com/',
      img: './img/hiib-event.jpg',
    },
  ]
});

// const workList = document.getElementById('folios');

const mainListFirst = new Vue({
  el: '#folios',
  data: folioList,
});

// let mainList = new Vue({
//   el: '__',
//   data: folioList,
// });