const siteUrl = 'https://ljhren.github.io';

const folioList = Object.freeze({
  contents: [
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'NCSOFT',
      date: '2022-07 ~ 2022-08',
      title: 'NC PLAY NOVEL TL Story Map 페이지 구축',
      description: '',
      outLink: 'https://about.ncsoft.com/play-novel',
      innerLink: '/project/playnovel/',
      img: `${siteUrl}/img/nc-playnovel.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: '네이버(주)',
      date: '2021-11 ~ 2022-01',
      title: 'NAVER VIBE 서비스 소개 페이지 리뉴얼',
      description: '',
      outLink: 'https://vibe.naver.com/about/',
      innerLink: '/project/vibe/',
      img: `${siteUrl}/img/vibe.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2021-11 ~ 2022-01',
      title: 'NCP NAVER Cloud Summit 2021 웹사이트 구축 및 운영',
      description: '',
      outLink: 'https://www.ncloud-online.com/navercloudsummit2021/',
      innerLink: '/project/ncs2021/',
      img: `${siteUrl}/img/aisummit_2021.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'PC Only',
      client: 'CJ',
      date: '2021-09 ~ 2021-11',
      title: 'M3(mnet smart+) 웹사이트 부분 구축',
      description: 'Main, Artist > Board, Contents, Vote 페이지',
      outLink: 'https://smart.mnetjp.com/',
      innerLink: '/project/m3/',
      img: `${siteUrl}/img/mnet-smart.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2021-08 ~ 2021-12',
      title: 'NCP GAME X CONFERENCE 2021 웹사이트 구축 및 운영',
      description: '',
      outLink: 'https://www.gamex.game/',
      innerLink: '/project/gamex/',
      img: `${siteUrl}/img/gamex.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Mobile Only',
      client: '아모레퍼시픽',
      date: '2021-05 ~ 2021-07',
      title: '그린사이클 캠페인 마이크로사이트 기능 개발',
      description: '',
      outLink: '',
      innerLink: '/project/greencycle/',
      img: `${siteUrl}/img/amore_greencycle.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: '(주)에코엑스랩',
      date: '2021-04 ~ 2021-04',
      title: 'ECOEX LAB 웹사이트 리뉴얼',
      description: '',
      outLink: 'https://ecoex.kr/',
      innerLink: '/project/ecoex/',
      img: `${siteUrl}/img/ecoex.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Adaptive',
      client: 'DL Holdings',
      date: '2020-11 ~ 2021-02',
      title: 'DL Holdings 웹사이트 구축',
      description: '',
      outLink: 'https://www.dlholdings.co.kr/ko/index.do',
      innerLink: '/project/dlholdings/',
      img: `${siteUrl}/img/dlholdings.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build, Manage',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2020-11 ~ 2021-06',
      title: '네이버클라우드 웹사이트 리뉴얼 및 운영',
      description: '',
      outLink: 'https://navercloudcorp.com/',
      innerLink: '/project/navercloudcorp/',
      img: `${siteUrl}/img/navercloudcorp.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'profit',
      date: '2020-11 ~ 2020-12',
      title: 'profit 웹/태블릿 UI 개발(React)',
      description: '',
      outLink: '',
      innerLink: '/project/profit/',
      img: `${siteUrl}/img/profit.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: 'SK그룹',
      date: '2020-09 ~ 2020-11',
      title: 'SK ICT TECH SUMMIT 2020 웹사이트 구축',
      description: '',
      outLink: '',
      innerLink: '/project/sksummit/',
      img: `${siteUrl}/img/sk_ict-summit.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Responsive',
      client: '네이버클라우드 주식회사',
      date: '2020-09 ~ 2020-12',
      title: 'NCP NAVER Cloud Summit 2020 웹사이트 구축 및 운영',
      description: '',
      outLink: 'https://www.ncloud-online.com/aisummit/',
      innerLink: '/project/ncs2020',
      img: `${siteUrl}/img/aisummit_2020.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Build',
      siteInfo: 'Tablet Only',
      client: 'POSCO 건설',
      date: '2020-05 ~ 2020-06',
      title: '더샵갤러리 홍보 어플리케이션 웹뷰 제작',
      description: '',
      outLink: '',
      innerLink: '/project/thesharp/',
      img: `${siteUrl}/img/thesharp-gallery.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Manage',
      siteInfo: 'Responsive',
      client: '디엘이앤씨㈜',
      date: '2020-03 ~ 2020-10',
      title: '대림산업 ACRO 아크로라이프 웹사이트 운영',
      description: '',
      outLink: '',
      innerLink: '/project/acro/',
      img: `${siteUrl}/img/acro.jpg`,
    },
    {
      type: 'Publishing',
      typeDetail: 'Manage',
      siteInfo: 'Adaptive',
      client: 'DDB Korea, 하이투자증권(DGB)',
      date: '2020-03 ~ 2022-09',
      title: '하이투자증권 이벤트 웹사이트 연간 운영',
      description: '',
      outLink: 'https://event-hi-ib.com/',
      innerLink: '/project/hiib/',
      img: `${siteUrl}/img/hiib-event.jpg`,
    },
  ]
});

// const workList = document.getElementById('folios');

const mainListFirst = new Vue({
  el: '#folios',
  data: folioList,
});

const detailList = new Vue({
  el: '.folio-detail-wrap',
  data: folioList,
});

// let mainList = new Vue({
//   el: '__',
//   data: folioList,
// });